/**
 * `wilanis fuzz` and `wilanis regress`: many runs of a trigger against stubbed effects, each written out as a scenario,
 * and those scenarios replayed to say whether the tree still answers as it did.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { LoadResult } from '@wilanis/core';
import { type ScenarioDoc, schemaUrl } from '@wilanis/core';
import type { Report } from '@wilanis/engine';
import { embedderFor, generatedFire } from './stubbing.js';

// ---- fuzz / regress ----------------------------------------------------------------------------------

function pick(report: Report, prefix = ''): ScenarioDoc['expect']['nodes'] {
  const out: ScenarioDoc['expect']['nodes'] = {};
  for (const [id, n] of Object.entries(report.nodes)) {
    const key = prefix ? `${prefix}.${id}` : id;
    out[key] = {
      status: n.status,
      ...(n.selected ? { selected: n.selected } : {}),
      ...(n.status === 'done' && n.out !== undefined ? { out: n.out } : {}),
    };
    if (n.sub) Object.assign(out, pick(n.sub, key));
  }
  return out;
}

/** Run each trigger under N seeds with stubbed effects and write one scenario per run. */
export async function fuzz(
  load: LoadResult,
  opts: { runs?: number; profile?: string; out?: string } = {},
): Promise<string[]> {
  const written: string[] = [];
  const dir = join(load.root, opts.out ?? 'scenarios');
  mkdirSync(dir, { recursive: true });
  for (const t of load.registry.all('trigger')) {
    for (let seed = 1; seed <= (opts.runs ?? 5); seed++) {
      const record: Record<string, unknown> = {};
      const emb = embedderFor(load, { seed, record, profile: opts.profile });
      const { input, request } = generatedFire(emb, t, seed);
      const report = await emb.fire(t.doc, input, request);
      const sc: ScenarioDoc = {
        $schema: schemaUrl('scenario'),
        description: `${t.path} under seed ${seed}: ${report.status}. Generated by wilanis fuzz; edit stubs to pin an edge case.`,
        trigger: t.path,
        seed,
        in: input,
        request,
        stubs: record,
        expect: {
          status: report.status,
          ...(report.status === 'done' ? { output: report.output } : {}),
          nodes: pick(report),
        },
      };
      const file = join(dir, `${t.name}.${seed}.scenario.json`);
      writeFileSync(file, `${JSON.stringify(sc, null, 2)}\n`);
      written.push(file);
    }
  }
  return written;
}

const same = (a: unknown, b: unknown) => JSON.stringify(a) === JSON.stringify(b);

/** Replay every scenario with its recorded stubs and diff the report node by node. */
export async function regress(
  load: LoadResult,
  opts: { profile?: string } = {},
): Promise<{ ok: boolean; lines: string[] }> {
  const lines: string[] = [];
  let ok = true;
  const emb = embedderFor(load, { seed: 0, profile: opts.profile, env: fakeEnvFor(load) });
  for (const sc of load.registry.all('scenario')) {
    const trigger = load.registry.all('trigger').find(t => t.path === load.resolve(sc.doc.trigger));
    // S001 has already refused a scenario whose trigger is gone; skip rather than replay nothing.
    if (!trigger) {
      ok = false;
      lines.push(`${sc.path}: names unknown trigger '${sc.doc.trigger}'`);
      continue;
    }
    const report: Report = await emb.fire(trigger.doc, sc.doc.in, sc.doc.request ?? {}, { stubs: sc.doc.stubs });
    const diffs: string[] = [];
    if (report.status !== sc.doc.expect.status) diffs.push(`status ${sc.doc.expect.status} → ${report.status}`);
    if (sc.doc.expect.status === 'done' && !same(report.output, sc.doc.expect.output)) diffs.push('output changed');
    const got = pick(report);
    for (const [id, e] of Object.entries(sc.doc.expect.nodes)) {
      const n = got[id];
      if (!n) {
        diffs.push(`${id}: gone`);
        continue;
      }
      if (n.status !== e.status) diffs.push(`${id}: ${e.status} → ${n.status}`);
      if (e.selected && n.selected !== e.selected) diffs.push(`${id}: routed ${e.selected} → ${n.selected}`);
      if ('out' in e && !same(n.out, e.out)) diffs.push(`${id}: out changed`);
    }
    for (const id of Object.keys(got)) if (!(id in sc.doc.expect.nodes)) diffs.push(`${id}: new`);
    if (diffs.length) ok = false;
    lines.push(`${sc.path}: ${diffs.length ? `DIFF ${diffs.join('; ')}` : 'same'}`);
  }
  return { ok, lines };
}

function fakeEnvFor(load: LoadResult): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = {};
  for (const v of Object.values(load.registry.project?.doc.secrets ?? {})) env[v] = `stub-${v.toLowerCase()}`;
  return env;
}
